import { Meta, StoryObj } from '@storybook/react-vite';
import { TimePicker } from './time-picker';
declare const meta: Meta<typeof TimePicker>;
export default meta;
type Story = StoryObj<typeof TimePicker>;
export declare const AnalogMode: Story;
export declare const BorderAndFooterManagement: Story;
export declare const Default: Story;
export declare const WithValue: Story;
export declare const Variants: Story;
export declare const Sizes: Story;
export declare const TwelveHourFormat: Story;
export declare const WithSeconds: Story;
export declare const TwelveHourWithSeconds: Story;
export declare const MinuteSteps: Story;
export declare const WithLabelAndError: Story;
export declare const Disabled: Story;
export declare const Playground: Story;
export declare const InnerLabel: Story;
