import { Meta, StoryObj } from '@storybook/react-vite';
import { Dropdown } from './dropdown';
declare const meta: Meta<typeof Dropdown>;
export default meta;
type Story = StoryObj<typeof Dropdown>;
export declare const Default: Story;
export declare const MultiSelect: Story;
export declare const Searchable: Story;
export declare const HoverTrigger: Story;
export declare const RichUI: Story;
export declare const LazyLoading: Story;
export declare const ContextMenu: Story;
export declare const LoadingState: Story;
export declare const CustomVariants: Story;
