import { Meta, StoryObj } from '@storybook/react-vite';
import { Input } from './input';
declare const meta: Meta<typeof Input>;
export default meta;
type Story = StoryObj<typeof Input>;
export declare const Default: Story;
export declare const ShortHandIcon: Story;
export declare const Variants: Story;
export declare const WithIcons: Story;
export declare const SearchInput: Story;
export declare const PasswordField: Story;
export declare const ValidationStates: Story;
export declare const PhoneInput: Story;
export declare const UrlInput: Story;
export declare const Loading: Story;
export declare const Sizes: Story;
export declare const PaymentInput: Story;
export declare const CompactStyle: Story;
export declare const Multiline: Story;
export declare const CharacterLimits: Story;
export declare const OTPField: Story;
