import { Meta, StoryObj } from '@storybook/react-vite';
import { Accordion } from './accordion';
import { default as React } from '../../../node_modules/react';
declare const meta: Meta<typeof Accordion>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const Bordered: Story;
export declare const Separated: Story;
export declare const Filled: Story;
export declare const Ghost: Story;
export declare const Small: Story;
export declare const Large: Story;
export declare const CustomIcons: Story;
export declare const ArrowOnLeft: Story;
export declare const IconsOnRight: Story;
export declare const FullRounded: Story;
export declare const DisabledItems: Story;
export declare const CustomColors: Story;
export declare const Controlled: React.FC;
