import { Meta, StoryObj } from '@storybook/react';
import { Checkbox } from './checkbox';
declare const meta: Meta<typeof Checkbox>;
export default meta;
type Story = StoryObj<typeof Checkbox>;
export declare const Default: Story;
export declare const Variants: () => import("react/jsx-runtime").JSX.Element;
export declare const Sizes: () => import("react/jsx-runtime").JSX.Element;
export declare const WithDescription: Story;
export declare const Indeterminate: () => import("react/jsx-runtime").JSX.Element;
export declare const States: () => import("react/jsx-runtime").JSX.Element;
export declare const Group: () => import("react/jsx-runtime").JSX.Element;
