import { Meta, StoryObj } from '@storybook/react-vite';
import { Table } from './table';
declare const meta: Meta<typeof Table>;
export default meta;
type Story = StoryObj<typeof Table>;
export declare const Enterprise: Story;
export declare const GroupedHeaders: Story;
export declare const InfiniteScroll: Story;
export declare const LoadingState: Story;
export declare const EmptyState: Story;
