import { Meta, StoryObj } from '@storybook/react-vite';
import { CalendarDatePicker } from './calendar-date-picker';
declare const meta: Meta<typeof CalendarDatePicker>;
export default meta;
type Story = StoryObj<typeof CalendarDatePicker>;
export declare const Default: Story;
export declare const WithHeaderLabel: Story;
export declare const NoHeader: Story;
export declare const CustomInnerLabel: Story;
export declare const DayBorderRadius: Story;
export declare const DefaultFooterActions: Story;
export declare const CustomFooterActions: Story;
export declare const FooterActionsNoIcons: Story;
export declare const Variants: Story;
export declare const Sizes: Story;
export declare const WithLabelAndHelper: Story;
export declare const ErrorState: Story;
export declare const CardCustomization: Story;
export declare const BorderAndFooterManagement: Story;
export declare const Disabled: Story;
export declare const MinMaxDates: Story;
export declare const DisplayFormats: Story;
export declare const Playground: Story;
